const express = require('express');
const router = express.Router();
const bnController = require('../controllers/BannerController');
const upload = require('../utils/saveIMG');
const mdw = require('../utils/midleware');
router.get('/home', mdw.check_admin, bnController.home);
router.get('/add', mdw.check_admin, bnController.add);
router.post('/add', mdw.check_admin, upload.single('image'), bnController.store);
router.delete('/delete/:_id', mdw.check_admin, bnController.delete);
router.get('/info/:_id', mdw.check_admin, bnController.info);
router.put('/update/:_id', mdw.check_admin, upload.single('image'), bnController.update);
module.exports = router;